### ISSUE TITLE
Figure out which version of Godot to Run on CI

### ISSUE THREAD

**Issue by CodeDarigan** [CodeDarigan/WAT-Mono#13]
Maybe the non headless versions work if we just delete all the import files?

Alternatively maybe we could use the server for it?

**Comment by CodeDarigan** [comment]
Seems our previous version worked fine because it was only GDScript Asserts. The issue is to do with C# Testing. 

Maybe we could precompile a binary and run tests from there instead?

**Comment by m50** [comment]
Don't know if this will help, but this is the job I am using to run my WAT-Mono tests:
```yaml
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
      - name: Compile
        run: msbuild
      - name: Run Tests
        run: godot addons/WAT/cli.tscn -run_dir=Tests
```
